version: '3'

services:
  db:
    image: mongo:3.4.2
    ports:
      - "27017:27017"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: minio server /data
  web:
    build: .
    command: node index.js
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
      - minio
